"""Field disposition ledger -- what is filled, what cannot be, and why.

Joins `schema/e19_disposition.yaml` (a claim about each column) to measured
coverage in `data/processed/e19/` (what is actually there) and emits
`docs/e19_field_ledger.md`.

The number this exists to produce is **percent of obtainable fields filled**.
Raw fill percentage is not that number and never was: most empty cells in these
tables are empty because a BSEE investigation report structurally cannot answer
the question, and reporting those alongside genuine gaps makes both illegible.

Run::

    uv run python -m psm.ledger
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
E19 = REPO / "data" / "processed" / "e19"
DISPOSITION = REPO / "schema" / "e19_disposition.yaml"
DEFAULT_OUT = REPO / "docs" / "e19_field_ledger.md"

# Counted in the denominator of "obtainable". `needs_human` is the labelling
# backlog and `deliberate_blank` is a decision, not a gap; including either
# would make the headline move when we take on work or make a judgement call,
# which is exactly what it must not do.
OBTAINABLE = ("filled", "synthetic")
ALL_DISPOSITIONS = ("filled", "synthetic", "needs_human", "deliberate_blank", "not_obtainable")

ORDER = ["incidents", "causes", "recommendations", "closeout"]


def _read(table: str) -> list[dict]:
    """Prefer the enriched table; fall back to the verbatim one."""
    csv.field_size_limit(10 ** 9)
    for path in (E19 / "enriched" / f"{table}.csv", E19 / f"{table}.csv"):
        if path.exists():
            with path.open(encoding="utf-8", newline="") as fh:
                return list(csv.DictReader(fh))
    return []


def measure() -> dict[str, dict[str, tuple[int, int]]]:
    """(filled_cells, total_rows) per table, per column."""
    out: dict[str, dict[str, tuple[int, int]]] = {}
    for table in ORDER:
        rows = _read(table)
        if not rows:
            continue
        out[table] = {c: (sum(1 for r in rows if (r[c] or "").strip()), len(rows))
                      for c in rows[0]}
    return out


def load_disposition() -> dict:
    return yaml.safe_load(DISPOSITION.read_text(encoding="utf-8"))


def reconcile(spec: dict, seen: dict) -> tuple[list[str], list[str]]:
    """Columns present in the data but absent from the file, and vice versa.

    A disposition file that has drifted from the data is worse than none: it
    reads as an audit while describing a table that no longer exists.
    """
    missing, orphan = [], []
    for table, cols in seen.items():
        declared = set(spec["fields"].get(table, {}))
        for c in cols:
            if c not in declared:
                missing.append(f"{table}.{c!r}")
        for c in declared - set(cols):
            orphan.append(f"{table}.{c!r}")
    return sorted(missing), sorted(orphan)


def tally(spec: dict, seen: dict) -> dict:
    counts = {d: 0 for d in ALL_DISPOSITIONS}
    obtainable = filled_obtainable = 0
    cells_filled = cells_possible = 0
    for table, cols in seen.items():
        for col, (n, total) in cols.items():
            entry = spec["fields"].get(table, {}).get(col)
            if not entry:
                continue
            d = entry["disposition"]
            counts[d] += 1
            if d in OBTAINABLE:
                obtainable += 1
                cells_possible += total
                cells_filled += n
                if n:
                    filled_obtainable += 1
    return {
        "counts": counts,
        "obtainable_fields": obtainable,
        "obtainable_fields_filled": filled_obtainable,
        "obtainable_cells": cells_possible,
        "obtainable_cells_filled": cells_filled,
        "total_fields": sum(counts.values()),
    }


def render(spec: dict, seen: dict, stats: dict) -> str:
    L: list[str] = []
    A = L.append
    A("# E19 field ledger\n")
    A("Generated by `psm.ledger`. Do not edit by hand -- edit "
      "`schema/e19_disposition.yaml` and regenerate.\n")
    A("## The headline\n")
    f, o = stats["obtainable_fields_filled"], stats["obtainable_fields"]
    cf, co = stats["obtainable_cells_filled"], stats["obtainable_cells"]
    A(f"**{f} of {o} obtainable fields carry data ({100 * f / o:.0f}%).**\n")
    A(f"Cell-level, across those fields: {cf:,} of {co:,} ({100 * cf / co:.1f}%). "
      "The field number says whether a column was attempted; the cell number "
      "says how far a BSEE report typically gets. Both matter and they are not "
      "the same claim.\n")
    A(f"Of {stats['total_fields']} columns in total:\n")
    for d in ALL_DISPOSITIONS:
        A(f"- **{d}** — {stats['counts'][d]}")
    A("")
    A("`needs_human` and `deliberate_blank` are deliberately outside the "
      "denominator. Including them would make the headline move whenever we "
      "take on labelling work or make a judgement call, which is precisely "
      "what it must not do.\n")

    for table in ORDER:
        cols = seen.get(table)
        if not cols:
            continue
        A(f"## `{table}`\n")
        A("| fill | disposition | column | note |")
        A("|---|---|---|---|")
        entries = spec["fields"].get(table, {})
        def key(item):
            col = item[0]
            e = entries.get(col)
            d = e["disposition"] if e else "zzz"
            return (ALL_DISPOSITIONS.index(d) if d in ALL_DISPOSITIONS else 9,
                    -cols[col][0])
        for col, (n, total) in sorted(cols.items(), key=key):
            e = entries.get(col)
            d = e["disposition"] if e else "**UNDECLARED**"
            note = " ".join(str(e.get("note", "") if e else "").split())
            if e and e.get("generator") is None and e.get("disposition") == "synthetic":
                note = (note + " No generator yet.").strip()
            elif e and e.get("generator"):
                note = (note + f" Generator: `{e['generator']}`.").strip()
            A(f"| {100 * n / total:.1f}% | {d} | `{col}` | {note} |")
        A("")

    missing, orphan = reconcile(spec, seen)
    if missing or orphan:
        A("## Drift\n")
        for m in missing:
            A(f"- **undeclared in the disposition file:** {m}")
        for o_ in orphan:
            A(f"- **declared but absent from the data:** {o_}")
        A("")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)

    spec = load_disposition()
    seen = measure()
    if not seen:
        print("no E19 tables found -- run `python -m psm.project` first")
        return 1
    stats = tally(spec, seen)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(spec, seen, stats), encoding="utf-8")

    f, o = stats["obtainable_fields_filled"], stats["obtainable_fields"]
    cf, co = stats["obtainable_cells_filled"], stats["obtainable_cells"]
    print(f"wrote {args.out}")
    print(f"  obtainable fields filled : {f}/{o} = {100 * f / o:.0f}%")
    print(f"  obtainable cells filled  : {cf:,}/{co:,} = {100 * cf / co:.1f}%")
    print(f"  dispositions             : {stats['counts']}")
    missing, orphan = reconcile(spec, seen)
    for m in missing:
        print(f"  UNDECLARED: {m}")
    for o_ in orphan:
        print(f"  ORPHAN:     {o_}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
